
import { Cheese } from './types';

export const INITIAL_CHEESES: Cheese[] = [
  // === М'ЯКІ ТА КРАФТОВІ (УКРАЇНА) - 15 ПОЗИЦІЙ ===
  { id: 'ua-s-1', name: 'Чорна Башта (Сироман)', type: 'Soft-Ripened', milk: 'Goat', origin: 'Ukrainian', region: 'Київщина', agingMonths: 1, intensity: 3, texture: 2, saltiness: 2, pungency: 3, flavorProfile: 'Грибний, попіл, вершки', bestPairing: 'Біле вино, багет', pricePer100g: 135 },
  { id: 'ua-s-2', name: 'Реп’ях (Сироман)', type: 'Washed-Rind', milk: 'Cow', origin: 'Ukrainian', region: 'Київщина', agingMonths: 2, intensity: 5, texture: 2, saltiness: 3, pungency: 5, flavorProfile: 'Тваринний, гострий, пікантний', bestPairing: 'Міцний ель', pricePer100g: 145 },
  { id: 'ua-s-3', name: 'Святослав (Доообра ферма)', type: 'Soft-Ripened', milk: 'Cow', origin: 'Ukrainian', region: 'Київщина', agingMonths: 1, intensity: 3, texture: 2, saltiness: 2, pungency: 2, flavorProfile: 'Грибний, вогкий підлісок', bestPairing: 'Рожеве вино', pricePer100g: 115 },
  { id: 'ua-s-4', name: 'Брі (Zinka)', type: 'Soft-Ripened', milk: 'Goat', origin: 'Ukrainian', region: 'Київщина', agingMonths: 1, intensity: 2, texture: 1, saltiness: 2, pungency: 2, flavorProfile: 'Ніжний, молочний, горіх', bestPairing: 'Шампанське', pricePer100g: 105 },
  { id: 'ua-s-5', name: 'Камамбер (Мукко)', type: 'Soft-Ripened', milk: 'Cow', origin: 'Ukrainian', region: 'Львівщина', agingMonths: 1, intensity: 4, texture: 1, saltiness: 2, pungency: 4, flavorProfile: 'Аміачний, гриби, земля', bestPairing: 'Сидр', pricePer100g: 95 },
  { id: 'ua-s-6', name: 'Валок (Станіславська)', type: 'Soft-Ripened', milk: 'Cow', origin: 'Ukrainian', region: 'Франківщина', agingMonths: 2, intensity: 3, texture: 2, saltiness: 3, pungency: 3, flavorProfile: 'Трави, квіти, вершки', bestPairing: 'Світле пиво', pricePer100g: 120 },
  { id: 'ua-s-7', name: 'Шеврет (Еко-ферма)', type: 'Soft-Ripened', milk: 'Goat', origin: 'Ukrainian', region: 'Закарпаття', agingMonths: 1, intensity: 3, texture: 1, saltiness: 2, pungency: 3, flavorProfile: 'Лимон, козячий, свіжий', bestPairing: 'Мед', pricePer100g: 130 },
  { id: 'ua-s-8', name: 'М’яка Ватра', type: 'Soft-Ripened', milk: 'Cow', origin: 'Ukrainian', region: 'Карпати', agingMonths: 1, intensity: 2, texture: 2, saltiness: 2, pungency: 2, flavorProfile: 'Молочна піна, солодощі', bestPairing: 'Ягоди', pricePer100g: 85 },
  { id: 'ua-s-9', name: 'Трюфельний Сон', type: 'Soft-Ripened', milk: 'Cow', origin: 'Ukrainian', region: 'Черкащина', agingMonths: 1, intensity: 4, texture: 2, saltiness: 2, pungency: 4, flavorProfile: 'Трюфель, земля, вершки', bestPairing: 'М’ясо', pricePer100g: 160 },
  { id: 'ua-s-10', name: 'Білий Камінь', type: 'Soft-Ripened', milk: 'Mixed', origin: 'Ukrainian', region: 'Полтавщина', agingMonths: 1, intensity: 3, texture: 1, saltiness: 2, pungency: 2, flavorProfile: 'Складний, трав’яний', bestPairing: 'Фрукти', pricePer100g: 140 },
  { id: 'ua-s-11', name: 'Пліснява Говерли', type: 'Soft-Ripened', milk: 'Sheep', origin: 'Ukrainian', region: 'Закарпаття', agingMonths: 2, intensity: 4, texture: 2, saltiness: 3, pungency: 3, flavorProfile: 'Овечий, масляний, гриби', bestPairing: 'Червоне вино', pricePer100g: 170 },
  { id: 'ua-s-12', name: 'Рудий (Сироман)', type: 'Washed-Rind', milk: 'Goat', origin: 'Ukrainian', region: 'Київщина', agingMonths: 2, intensity: 5, texture: 2, saltiness: 3, pungency: 5, flavorProfile: 'Ферма, гострий, козячий', bestPairing: 'Бурбон', pricePer100g: 155 },
  { id: 'ua-s-13', name: 'Крем-сир Поділля', type: 'Fresh', milk: 'Cow', origin: 'Ukrainian', region: 'Вінниччина', agingMonths: 0, intensity: 1, texture: 1, saltiness: 1, pungency: 1, flavorProfile: 'Вершковий, чистий', bestPairing: 'Тости', pricePer100g: 65 },
  { id: 'ua-s-14', name: 'Золота Коза (М’який)', type: 'Soft-Ripened', milk: 'Goat', origin: 'Ukrainian', region: 'Кіровоградщина', agingMonths: 1, intensity: 2, texture: 1, saltiness: 1, pungency: 2, flavorProfile: 'Делікатний, молочний', bestPairing: 'Горіхи', pricePer100g: 110 },
  { id: 'ua-s-15', name: 'Капра (Брі)', type: 'Soft-Ripened', milk: 'Goat', origin: 'Ukrainian', region: 'Тернопільщина', agingMonths: 1, intensity: 3, texture: 2, saltiness: 2, pungency: 3, flavorProfile: 'Трави, цитрус', bestPairing: 'Ігристе', pricePer100g: 125 },

  // === ТВЕРДІ ТА ВИТРИМАНІ (УКРАЇНА) - 15 ПОЗИЦІЙ ===
  { id: 'ua-h-1', name: 'Легенда (Доообра ферма)', type: 'Hard', milk: 'Cow', origin: 'Ukrainian', region: 'Черкащина', agingMonths: 12, intensity: 4, texture: 5, saltiness: 3, pungency: 2, flavorProfile: 'Горіховий, карамельний', bestPairing: 'Стаут, віскі', pricePer100g: 110 },
  { id: 'ua-h-2', name: 'Нарцис Карпат', type: 'Hard', milk: 'Cow', origin: 'Ukrainian', region: 'Закарпаття', agingMonths: 6, intensity: 4, texture: 4, saltiness: 3, pungency: 3, flavorProfile: 'Альпійські трави, квіти', bestPairing: 'Ріслінг', pricePer100g: 100 },
  { id: 'ua-h-3', name: 'Мукко 18 міс', type: 'Hard', milk: 'Cow', origin: 'Ukrainian', region: 'Львівщина', agingMonths: 18, intensity: 5, texture: 5, saltiness: 4, pungency: 3, flavorProfile: 'Кристали солі, пікантний', bestPairing: 'Коньяк', pricePer100g: 130 },
  { id: 'ua-h-4', name: 'Біласовиця (Sheep)', type: 'Hard', milk: 'Sheep', origin: 'Ukrainian', region: 'Карпати', agingMonths: 12, intensity: 5, texture: 5, saltiness: 5, pungency: 4, flavorProfile: 'Овечий, жирний, масляний', bestPairing: 'Червоне сухе', pricePer100g: 175 },
  { id: 'ua-h-5', name: 'Золота Коза Екстра', type: 'Hard', milk: 'Goat', origin: 'Ukrainian', region: 'Кіровоградщина', agingMonths: 9, intensity: 4, texture: 5, saltiness: 3, pungency: 4, flavorProfile: 'Сухофрукти, козячий', bestPairing: 'Портвейн', pricePer100g: 140 },
  { id: 'ua-h-6', name: 'Чеддер (Zinka)', type: 'Hard', milk: 'Goat', origin: 'Ukrainian', region: 'Київщина', agingMonths: 6, intensity: 4, texture: 4, saltiness: 3, pungency: 3, flavorProfile: 'Кислуватий, гострий', bestPairing: 'Сідр', pricePer100g: 115 },
  { id: 'ua-h-7', name: 'Гауда Мукко (Чилі)', type: 'Hard', milk: 'Cow', origin: 'Ukrainian', region: 'Львівщина', agingMonths: 3, intensity: 4, texture: 4, saltiness: 3, pungency: 4, flavorProfile: 'Перцевий, пряний', bestPairing: 'Темне пиво', pricePer100g: 90 },
  { id: 'ua-h-8', name: 'Пармезан (Гарбузовий рай)', type: 'Hard', milk: 'Cow', origin: 'Ukrainian', region: 'Львівщина', agingMonths: 10, intensity: 4, texture: 5, saltiness: 4, pungency: 2, flavorProfile: 'Фруктовий, ананас, твердий', bestPairing: 'Паста', pricePer100g: 125 },
  { id: 'ua-h-9', name: 'Вільний Козак', type: 'Hard', milk: 'Cow', origin: 'Ukrainian', region: 'Хмельниччина', agingMonths: 8, intensity: 4, texture: 4, saltiness: 3, pungency: 3, flavorProfile: 'Трави, земля, гриби', bestPairing: 'Горілка', pricePer100g: 95 },
  { id: 'ua-h-10', name: 'Сирний Мандрівник', type: 'Hard', milk: 'Mixed', origin: 'Ukrainian', region: 'Полтавщина', agingMonths: 5, intensity: 3, texture: 4, saltiness: 2, pungency: 2, flavorProfile: 'М’який вершковий горіх', bestPairing: 'Чай', pricePer100g: 105 },
  { id: 'ua-h-11', name: 'Овеча Радість', type: 'Hard', milk: 'Sheep', origin: 'Ukrainian', region: 'Одещина', agingMonths: 7, intensity: 5, texture: 5, saltiness: 4, pungency: 4, flavorProfile: 'Дуже жирний, дикий', bestPairing: 'Овочі гриль', pricePer100g: 180 },
  { id: 'ua-h-12', name: 'Старий Львів', type: 'Hard', milk: 'Cow', origin: 'Ukrainian', region: 'Львівщина', agingMonths: 12, intensity: 4, texture: 5, saltiness: 3, pungency: 2, flavorProfile: 'Кавовий присмак, іриска', bestPairing: 'Кава', pricePer100g: 110 },
  { id: 'ua-h-13', name: 'Гірський Крафт', type: 'Hard', milk: 'Cow', origin: 'Ukrainian', region: 'Карпати', agingMonths: 15, intensity: 5, texture: 5, saltiness: 4, pungency: 3, flavorProfile: 'Кристали, хрусткий, мед', bestPairing: 'Вино Каберне', pricePer100g: 140 },
  { id: 'ua-h-14', name: 'Козячий Гурман', type: 'Hard', milk: 'Goat', origin: 'Ukrainian', region: 'Київщина', agingMonths: 10, intensity: 4, texture: 5, saltiness: 3, pungency: 4, flavorProfile: 'Мускус, квіти, горіх', bestPairing: 'Біле сухе', pricePer100g: 135 },
  { id: 'ua-h-15', name: 'Український Емменталь', type: 'Hard', milk: 'Cow', origin: 'Ukrainian', region: 'Волинь', agingMonths: 4, intensity: 3, texture: 4, saltiness: 2, pungency: 2, flavorProfile: 'Солодкуватий, дірки, молоко', bestPairing: 'Бутерброди', pricePer100g: 80 },

  // === СВІЖІ ТА РОЗСІЛЬНІ (УКРАЇНА) - 15 ПОЗИЦІЙ ===
  { id: 'ua-f-1', name: 'Бринза Гуцульська (Козина)', type: 'Fresh', milk: 'Goat', origin: 'Ukrainian', region: 'Карпати', agingMonths: 0, intensity: 4, texture: 3, saltiness: 5, pungency: 4, flavorProfile: 'Гострий, солоний, козячий', bestPairing: 'Салат', pricePer100g: 65 },
  { id: 'ua-f-2', name: 'Бринза (Овеча)', type: 'Fresh', milk: 'Sheep', origin: 'Ukrainian', region: 'Карпати', agingMonths: 0, intensity: 5, texture: 3, saltiness: 5, pungency: 5, flavorProfile: 'Дуже солоний, димний', bestPairing: 'Банош', pricePer100g: 75 },
  { id: 'ua-f-3', name: 'Моцарелла (Amano)', type: 'Fresh', milk: 'Cow', origin: 'Ukrainian', region: 'Київщина', agingMonths: 0, intensity: 1, texture: 1, saltiness: 1, pungency: 1, flavorProfile: 'Вершки, свіже молоко', bestPairing: 'Томати', pricePer100g: 55 },
  { id: 'ua-f-4', name: 'Буратта (Сироварня)', type: 'Fresh', milk: 'Cow', origin: 'Ukrainian', region: 'Одещина', agingMonths: 0, intensity: 2, texture: 1, saltiness: 1, pungency: 1, flavorProfile: 'Рідке серце, жирні вершки', bestPairing: 'Бальзамік', pricePer100g: 110 },
  { id: 'ua-f-5', name: 'Сулугуні (Класичний)', type: 'Fresh', milk: 'Cow', origin: 'Ukrainian', region: 'Закарпаття', agingMonths: 0, intensity: 3, texture: 3, saltiness: 4, pungency: 2, flavorProfile: 'Тягучий, димний', bestPairing: 'Лаваш', pricePer100g: 45 },
  { id: 'ua-f-6', name: 'Халлумі (Zinka)', type: 'Fresh', milk: 'Goat', origin: 'Ukrainian', region: 'Київщина', agingMonths: 0, intensity: 2, texture: 4, saltiness: 3, pungency: 1, flavorProfile: 'Для смаження, м’ятний', bestPairing: 'Гриль', pricePer100g: 85 },
  { id: 'ua-f-7', name: 'Рікотта (Мукко)', type: 'Fresh', milk: 'Cow', origin: 'Ukrainian', region: 'Львівщина', agingMonths: 0, intensity: 1, texture: 1, saltiness: 1, pungency: 1, flavorProfile: 'Солодкий, сирний', bestPairing: 'Млинці', pricePer100g: 40 },
  { id: 'ua-f-8', name: 'Вурда (Sheep)', type: 'Fresh', milk: 'Sheep', origin: 'Ukrainian', region: 'Карпати', agingMonths: 0, intensity: 3, texture: 2, saltiness: 2, pungency: 2, flavorProfile: 'Солодка сироватка, дим', bestPairing: 'Полента', pricePer100g: 60 },
  { id: 'ua-f-9', name: 'Адигейський (Крафт)', type: 'Fresh', milk: 'Cow', origin: 'Ukrainian', region: 'Черкащина', agingMonths: 0, intensity: 1, texture: 2, saltiness: 2, pungency: 1, flavorProfile: 'Нейтральний, молочний', bestPairing: 'Сніданок', pricePer100g: 35 },
  { id: 'ua-f-10', name: 'Лабне в олії', type: 'Fresh', milk: 'Goat', origin: 'Ukrainian', region: 'Київщина', agingMonths: 0, intensity: 3, texture: 1, saltiness: 3, pungency: 3, flavorProfile: 'Пряний, кислий', bestPairing: 'Хліб', pricePer100g: 95 },
  { id: 'ua-f-11', name: 'Чечіль (Косичка)', type: 'Fresh', milk: 'Cow', origin: 'Ukrainian', region: 'Закарпаття', agingMonths: 0, intensity: 3, texture: 3, saltiness: 5, pungency: 3, flavorProfile: 'Волокнистий, солений', bestPairing: 'Пиво', pricePer100g: 50 },
  { id: 'ua-f-12', name: 'Страчателла (Local)', type: 'Fresh', milk: 'Cow', origin: 'Ukrainian', region: 'Київщина', agingMonths: 0, intensity: 2, texture: 1, saltiness: 1, pungency: 1, flavorProfile: 'Волокна в вершках', bestPairing: 'Піца', pricePer100g: 130 },
  { id: 'ua-f-13', name: 'Маскарпоне (UA)', type: 'Fresh', milk: 'Cow', origin: 'Ukrainian', region: 'Полтава', agingMonths: 0, intensity: 1, texture: 1, saltiness: 0, pungency: 1, flavorProfile: 'Дуже жирний, солодкий', bestPairing: 'Десерт', pricePer100g: 70 },
  { id: 'ua-f-14', name: 'Фета (Zinka)', type: 'Fresh', milk: 'Goat', origin: 'Ukrainian', region: 'Київщина', agingMonths: 1, intensity: 4, texture: 3, saltiness: 5, pungency: 3, flavorProfile: 'Лимонний, солоний', bestPairing: 'Оливки', pricePer100g: 100 },
  { id: 'ua-f-15', name: 'Будз свіжий', type: 'Fresh', milk: 'Sheep', origin: 'Ukrainian', region: 'Карпати', agingMonths: 0, intensity: 3, texture: 3, saltiness: 2, pungency: 2, flavorProfile: 'Димний, пружний', bestPairing: 'Овочі', pricePer100g: 55 },

  // === БЛАКИТНІ ТА ПЛІСНЯВІ (УКРАЇНА + ІМПОРТ) - 15 ПОЗИЦІЙ ===
  { id: 'blue-1', name: 'Roquefort Papillon', type: 'Blue', milk: 'Sheep', origin: 'Import', region: 'Франція', agingMonths: 4, intensity: 5, texture: 2, saltiness: 5, pungency: 5, flavorProfile: 'Гострий, металевий, пліснява', bestPairing: 'Солодке вино', pricePer100g: 210 },
  { id: 'blue-2', name: 'Gorgonzola Piccante', type: 'Blue', milk: 'Cow', origin: 'Import', region: 'Італія', agingMonths: 3, intensity: 5, texture: 3, saltiness: 4, pungency: 5, flavorProfile: 'Дуже пряний, грибний', bestPairing: 'Волоські горіхи', pricePer100g: 160 },
  { id: 'blue-3', name: 'Gorgonzola Dolce', type: 'Blue', milk: 'Cow', origin: 'Import', region: 'Італія', agingMonths: 2, intensity: 3, texture: 1, saltiness: 3, pungency: 3, flavorProfile: 'Вершковий, солодкий', bestPairing: 'Груша', pricePer100g: 155 },
  { id: 'blue-4', name: 'Stilton Blue', type: 'Blue', milk: 'Cow', origin: 'Import', region: 'Англія', agingMonths: 5, intensity: 4, texture: 4, saltiness: 3, pungency: 4, flavorProfile: 'Трав’яний, масляний', bestPairing: 'Портвейн', pricePer100g: 185 },
  { id: 'blue-5', name: 'Danablu (60%)', type: 'Blue', milk: 'Cow', origin: 'Import', region: 'Данія', agingMonths: 3, intensity: 4, texture: 3, saltiness: 5, pungency: 4, flavorProfile: 'Різкий, солоний', bestPairing: 'Темний хліб', pricePer100g: 95 },
  { id: 'blue-6', name: 'Saint Agur', type: 'Blue', milk: 'Cow', origin: 'Import', region: 'Франція', agingMonths: 2, intensity: 4, texture: 1, saltiness: 3, pungency: 3, flavorProfile: 'Кремовий, ніжний', bestPairing: 'Фрукти', pricePer100g: 170 },
  { id: 'blue-7', name: 'Bleu d\'Auvergne', type: 'Blue', milk: 'Cow', origin: 'Import', region: 'Франція', agingMonths: 4, intensity: 4, texture: 3, saltiness: 4, pungency: 4, flavorProfile: 'Трав’яний, гострий', bestPairing: 'Горіхи', pricePer100g: 140 },
  { id: 'blue-8', name: 'Fourme d\'Ambert', type: 'Blue', milk: 'Cow', origin: 'Import', region: 'Франція', agingMonths: 2, intensity: 3, texture: 2, saltiness: 3, pungency: 3, flavorProfile: 'Вершковий, м’яка пліснява', bestPairing: 'Мед', pricePer100g: 150 },
  { id: 'blue-9', name: 'Дана (Zinka)', type: 'Blue', milk: 'Goat', origin: 'Ukrainian', region: 'Київщина', agingMonths: 3, intensity: 4, texture: 3, saltiness: 4, pungency: 4, flavorProfile: 'Гострий козячий', bestPairing: 'Вино', pricePer100g: 130 },
  { id: 'blue-10', name: 'Блакитний (Станіславська)', type: 'Blue', milk: 'Cow', origin: 'Ukrainian', region: 'Франківщина', agingMonths: 2, intensity: 3, texture: 2, saltiness: 3, pungency: 3, flavorProfile: 'М’яка пліснява, гриби', bestPairing: 'Інжир', pricePer100g: 110 },
  { id: 'blue-11', name: 'Cambozola', type: 'Blue', milk: 'Cow', origin: 'Import', region: 'Німеччина', agingMonths: 1, intensity: 2, texture: 1, saltiness: 2, pungency: 2, flavorProfile: 'Суміш Брі та Блакитного', bestPairing: 'Крекер', pricePer100g: 120 },
  { id: 'blue-12', name: 'Dorblu (Classic)', type: 'Blue', milk: 'Cow', origin: 'Import', region: 'Німеччина', agingMonths: 3, intensity: 3, texture: 3, saltiness: 4, pungency: 3, flavorProfile: 'Класичний збалансований', bestPairing: 'Салат', pricePer100g: 80 },
  { id: 'blue-13', name: 'Bavaria Blu', type: 'Blue', milk: 'Cow', origin: 'Import', region: 'Німеччина', agingMonths: 1, intensity: 2, texture: 1, saltiness: 1, pungency: 2, flavorProfile: 'Вершковий, легкий', bestPairing: 'Фрукти', pricePer100g: 130 },
  { id: 'blue-14', name: 'Queso Valdeón', type: 'Blue', milk: 'Mixed', origin: 'Import', region: 'Іспанія', agingMonths: 3, intensity: 5, texture: 3, saltiness: 4, pungency: 5, flavorProfile: 'Горіхове листя, пряний', bestPairing: 'Херес', pricePer100g: 190 },
  { id: 'blue-15', name: 'Roncal Blue', type: 'Blue', milk: 'Sheep', origin: 'Import', region: 'Іспанія', agingMonths: 6, intensity: 5, texture: 4, saltiness: 5, pungency: 5, flavorProfile: 'Землистий, масляний', bestPairing: 'Мед', pricePer100g: 220 },

  // === ІМПОРТНА КЛАСИКА (БЕЗ БЛАКИТНИХ) - 15 ПОЗИЦІЙ ===
  { id: 'im-1', name: 'Parmigiano Reggiano 24m', type: 'Hard', milk: 'Cow', origin: 'Import', region: 'Італія', agingMonths: 24, intensity: 5, texture: 5, saltiness: 3, pungency: 2, flavorProfile: 'Фруктовий, ананас, твердий', bestPairing: 'Ігристе', pricePer100g: 185 },
  { id: 'im-2', name: 'Pecorino Romano', type: 'Hard', milk: 'Sheep', origin: 'Import', region: 'Італія', agingMonths: 12, intensity: 5, texture: 5, saltiness: 5, pungency: 4, flavorProfile: 'Дуже солоний, овечий', bestPairing: 'Паста', pricePer100g: 160 },
  { id: 'im-3', name: 'Manchego Curado', type: 'Hard', milk: 'Sheep', origin: 'Import', region: 'Іспанія', agingMonths: 9, intensity: 4, texture: 4, saltiness: 3, pungency: 3, flavorProfile: 'Трав’яний, масляний', bestPairing: 'Херес', pricePer100g: 175 },
  { id: 'im-4', name: 'Gouda Old Amsterdam', type: 'Hard', milk: 'Cow', origin: 'Import', region: 'Нідерланди', agingMonths: 18, intensity: 5, texture: 5, saltiness: 4, pungency: 2, flavorProfile: 'Карамель, іриска', bestPairing: 'Темне пиво', pricePer100g: 140 },
  { id: 'im-5', name: 'Gruyère AOP Reserve', type: 'Hard', milk: 'Cow', origin: 'Import', region: 'Швейцарія', agingMonths: 12, intensity: 4, texture: 5, saltiness: 2, pungency: 3, flavorProfile: 'Горіх, альпійські квіти', bestPairing: 'Фондю', pricePer100g: 195 },
  { id: 'im-6', name: 'Camembert de Normandie', type: 'Soft-Ripened', milk: 'Cow', origin: 'Import', region: 'Франція', agingMonths: 1, intensity: 5, texture: 1, saltiness: 2, pungency: 5, flavorProfile: 'Ферма, гриби, земля', bestPairing: 'Сідр', pricePer100g: 165 },
  { id: 'im-7', name: 'Brie de Meaux AOP', type: 'Soft-Ripened', milk: 'Cow', origin: 'Import', region: 'Франція', agingMonths: 1, intensity: 4, texture: 1, saltiness: 2, pungency: 4, flavorProfile: 'Землистий, насичений вершковий', bestPairing: 'Шардоне', pricePer100g: 180 },
  { id: 'im-8', name: 'Époisses AOP', type: 'Washed-Rind', milk: 'Cow', origin: 'Import', region: 'Франція', agingMonths: 2, intensity: 5, texture: 1, saltiness: 3, pungency: 5, flavorProfile: 'Сильний аромат, м’ясо, коньяк', bestPairing: 'Бургундське', pricePer100g: 240 },
  { id: 'im-9', name: 'Taleggio DOP', type: 'Washed-Rind', milk: 'Cow', origin: 'Import', region: 'Італія', agingMonths: 2, intensity: 4, texture: 2, saltiness: 3, pungency: 4, flavorProfile: 'Танжерин, вершки, фрукти', bestPairing: 'Фрукти', pricePer100g: 125 },
  { id: 'im-10', name: 'Burrata di Puglia', type: 'Fresh', milk: 'Buffalo', origin: 'Import', region: 'Італія', agingMonths: 0, intensity: 2, texture: 1, saltiness: 1, pungency: 1, flavorProfile: 'Найвищі вершки, молоко', bestPairing: 'Песто', pricePer100g: 210 },
  { id: 'im-11', name: 'Appenzeller Extra', type: 'Hard', milk: 'Cow', origin: 'Import', region: 'Швейцарія', agingMonths: 9, intensity: 5, texture: 5, saltiness: 4, pungency: 4, flavorProfile: 'Пряні трави, секретний розсіл', bestPairing: 'Світле вино', pricePer100g: 230 },
  { id: 'im-12', name: 'Mimolette Vielle', type: 'Hard', milk: 'Cow', origin: 'Import', region: 'Франція', agingMonths: 12, intensity: 5, texture: 5, saltiness: 3, pungency: 3, flavorProfile: 'Горіх, іриска, помаранч', bestPairing: 'Ель', pricePer100g: 180 },
  { id: 'im-13', name: 'Saint-Nectaire AOP', type: 'Semi-Soft', milk: 'Cow', origin: 'Import', region: 'Франція', agingMonths: 2, intensity: 3, texture: 2, saltiness: 2, pungency: 3, flavorProfile: 'Підлісок, горіх', bestPairing: 'Фрукти', pricePer100g: 155 },
  { id: 'im-14', name: 'Comte 18m', type: 'Hard', milk: 'Cow', origin: 'Import', region: 'Франція', agingMonths: 18, intensity: 4, texture: 5, saltiness: 2, pungency: 3, flavorProfile: 'Фруктовий, горіховий', bestPairing: 'Вино Юра', pricePer100g: 190 },
  { id: 'im-15', name: 'Grana Padano 16m', type: 'Hard', milk: 'Cow', origin: 'Import', region: 'Італія', agingMonths: 16, intensity: 3, texture: 5, saltiness: 3, pungency: 2, flavorProfile: 'Зернистий, солодкий горіх', bestPairing: 'Мед', pricePer100g: 130 }
];

export const CHEESE_TYPES = ['Fresh', 'Soft-Ripened', 'Semi-Soft', 'Hard', 'Blue', 'Washed-Rind'];
export const MILK_TYPES = ['Cow', 'Goat', 'Sheep', 'Buffalo', 'Mixed'];

export const FLAVOR_NOTES = [
  'Вершковий', 'Горіховий', 'Карамельний', 'Грибний', 'Землистий', 'Гострий', 
  'Солоний', 'Трав’яний', 'Димний', 'Фруктовий', 'Кислуватий', 'Пікантний', 
  'Квітковий', 'Тваринний', 'Солодкий', 'Дріжджовий', 'Трюфельний', 'Аміачний',
  'Металевий', 'Цитрусовий', 'Медовий'
];
